### PR TITLE
SLING-7966 - Enhance the CLI by adding tool informations and more descriptive options

### PR DESCRIPTION
**Pull request by simonetripodi**
initial checkin

### CODE REVIEW

**Comment by simonetripodi** [comment]
Hi there @bdelacretaz !
As requested, here it is the proposal about improving the Analyzer CLI.

Apache Commons-CLI replaced the the ASF licensed picocli (https://picocli.info/) which makes the args parsing setup less verbose.
Logging level can be selected by end users by enabling CLI options, a shutdown-hook has been added to report users memory usage.

HTH! :)

**Comment by cziegeler** [comment]
@simonetripodi This PR has currently merge conflicts, could you please redo it based on the latest?

**Comment by cziegeler** [comment]
@simonetripodi We're dropping the CLI for now from the analyser (see SLING-8058)

**Comment by bosschaert** [comment]
As the CLI is currently not used I'm closing this PR.

**Pull request closed without merging**
