### PR TITLE
SLING-7925 - Donate new AnalyzerTask which is able to validate APIs/Regions

### PR DESCRIPTION
**Pull request by simonetripodi**
initial checkin

### CODE REVIEW

**Comment by bosschaert** [comment]
Hi @simonetripodi thanks for this pull request! It looks good to me.
Would it be possible to also add some unit tests for the code please?

**Comment by simonetripodi** [comment]
Sure - Unit test would require mocking few components, I hope it would be OK!

**Comment by simonetripodi** [comment]
@bosschaert unit tests added on last commit!

**Comment by simonetripodi** [comment]
yahoo! 🥇

**Comment by dulvac** [comment]
> yahoo!
@simonetripodi , please no unnecessary references to commercial entities.

Kidding, congrats :)

**Comment by simonetripodi** [comment]
@dulvac AHAHAHAHAH :D

**Pull request merged**
