### PR TITLE
SLING-7929 - Create a distribution package for the Feature Analyser

### PR DESCRIPTION
**Pull request by simonetripodi**
initial checkin

### CODE REVIEW

**Comment by bdelacretaz** [comment]
Thanks for this! This pull request and its commits mix several changes, switching to picocli, adding a shutdown hook and the packaging setup. Could you split this into separate pull requests? It makes things easier to review and understand.

**Comment by simonetripodi** [comment]
Thanks a lot for jumping in to review @bdelacretaz , very appreciated! :)
Modifications below:
 * The switch from Apache Commons-CLI to Picocli is to have a better Analyser CLI presentation, easier args parsing, beautiful Help synopsis
 * The shutdown hook prints execution time and memory usage, nothing relevant;
are all concerning to the same packaging topic, they don't try to resolve a different topic - have a look at issue description on SLING-7929 for more details

The rest of additions are about creating `.zip` and `.tar.gz` packages.

**Comment by bdelacretaz** [comment]
Thanks for the explanations @simonetripodi and I agree with those changes! It's just that I'd like to see them in separate commits as they address distinct concerns.

**Comment by simonetripodi** [comment]
Closing this PR since it is replaced by a new one

**Pull request closed without merging**
