### PR TITLE
SLING-7929 - Create a distribution package for the Feature Analyser

### PR DESCRIPTION
**Pull request by simonetripodi**
initial checkin

### CODE REVIEW

**Comment by simonetripodi** [comment]
Hi there @bdelacretaz ,
as requested, a new commits which takes care of packaging the Apache Sling Analyzer only, without mixing CLI feature.
HTH! :)

**Comment by cziegeler** [comment]
@simonetripodi  Is it possible to create two jars - one that has just the class files from this project and the other one is the distribution with all dependencies?

**Comment by cziegeler** [comment]
@simonetripodi We're dropping the CLI for now from the analyser (see SLING-8058)

**Comment by bosschaert** [comment]
This PR is outdated.

**Pull request closed without merging**
